using UnityEngine;
using System.Collections;
using Unity.AI.Navigation;

/// <summary>
/// Generates a customizable procedural terrain using Perlin noise, optional falloff, and player-driven erosion. Also supports automatic NavMesh rebuilding and provides utility methods for sampling and clamping terrain positions.
/// </summary>

[RequireComponent(typeof(MeshFilter), typeof(MeshRenderer), typeof(MeshCollider))]
public class CustomMapGenerator : MonoBehaviour, IMapGenerator
{
    [Header("Map Settings")]
    [SerializeField] private int mapWidth = 200;
    [SerializeField] private int mapHeight = 200;
    [SerializeField] private float noiseScale = 20f; // Controls the zoom of the noise

    [Header("Noise Settings")]
    [SerializeField] private int octaves = 4; // Layers of noise 
    [Range(0, 1)][SerializeField] private float persistance = 0.5f; // Amplitude falloff per octave
    [SerializeField] private float lacunarity = 2f; // Frequency increase per octave
    [SerializeField] private int seed = 0; // Seed of map
    [SerializeField] private Vector2 offset; 

    [Header("Mesh Settings")]
    [SerializeField] private float meshHeightMultiplier = 5f; // Control the height values
    [SerializeField] private AnimationCurve meshHeightCurve = AnimationCurve.Linear(0, 0, 1, 1); // Smooths the terrain shape
    [SerializeField] private float meshScale = 1f; // The spacing between verticies

    [Header("Falloff Settings")]
    [SerializeField] private bool useFallOff = true; // Toggles island-like fading edges
    [Range(0, 1)][SerializeField] private float fallOffStrength = 0.5f; // Controls how strong the fade is

    [Header("Erosion Settings")]
    [SerializeField] private bool enablePlayerErosion = true; // Enables erosion caused by player movement
    [SerializeField] private Transform player; // Player reference for erosion source
    [SerializeField] private float minMoveDistance = 0.2f; // Distance player must move before erosion triggers
    [SerializeField] private float erosionRadius = 3f; // Radius around player affected by erosion
    [SerializeField] private float erosionStrength = 0.5f; // How deep erosion removes terrain
    [SerializeField] private float erosionFalloff = 3f; // Controls smoothness of erosion gradient

    [Header("References")]
    [SerializeField] private Material terrainMaterial; // Material applied to generated terrain

    private Mesh mesh; // The 3D mesh that forms the visible terrain surface in Unity.
    private MeshCollider meshCollider; // The collider that matches the terrain mesh, allowing physical interactions
    private NavMeshSurface navMeshSurface; // Handles NavMesh generation for AI navigation on the terrain surface.
    private Vector3[] vertices; // Stores all vertex positions that make up the mesh — used for shaping or modifying the terrain.
    private float[,] noiseMap; // A 2D array of height values generated by the Perlin noise function that defines terrain height variations.
    private Vector3 lastPlayerPos; // Tracks last player position to detect movement

    private void Awake()
    {
        // Initialise the player's last position
        if (player != null)
        {
            lastPlayerPos = player.position;
        }
    }

    // When the game starts
    private void Start()
    {
        // Generate the inital terrain mesh
        GenerateMap();

        // Ensure there's a NavMeshSurface for navigation
        navMeshSurface = GetComponent<NavMeshSurface>();
        if (navMeshSurface == null)
        {
            navMeshSurface = gameObject.AddComponent<NavMeshSurface>();
        }

        // Build the NavMesh now that the terrain exists
        navMeshSurface.BuildNavMesh();
    }

    // Updated every frame
    private void Update()
    {
        // Skip if erosion disabled or no player/mesh present
        if (enablePlayerErosion && player != null && mesh != null)
        {
            // Only apply erosion if the player has actually moved
            if ((player.position - lastPlayerPos).sqrMagnitude > minMoveDistance * minMoveDistance)
            {
                ApplyErosionAtPosition(player.position);
                lastPlayerPos = player.position;
            }
        }
    }

    [ContextMenu("Generate Map")]
    public void GenerateMap()
    {
        // Generate base Perlin noise map
        noiseMap = PerlinNoise.GenerateNoiseMap(mapWidth, mapHeight, seed, noiseScale, octaves, persistance, lacunarity, offset);

        // Optionally apply a falloff map for island-like terrain
        if (useFallOff)
        {
            float[,] falloffMap = FallOffGenerator.GenerateFallOffMap(mapWidth);
            for (int y = 0; y < mapHeight; y++)
            {
                for (int x = 0; x < mapWidth; x++)
                {
                    // Subtract falloff and clamp between 0-1
                    noiseMap[x, y] = Mathf.Clamp01(noiseMap[x, y] - falloffMap[x, y] * fallOffStrength);
                }
            }
        }

        // Convert heightmap into 3D mesh data
        MeshData meshData = MeshGenerator.GenerateTerrainMesh(noiseMap, meshHeightMultiplier, meshHeightCurve, meshScale);
        mesh = meshData.CreateMesh();

        // Apply to components
        GetComponent<MeshFilter>().mesh = mesh;
        meshCollider = GetComponent<MeshCollider>();
        meshCollider.sharedMesh = mesh;

        if (terrainMaterial != null)
        {
            GetComponent<MeshRenderer>().material = terrainMaterial;
        }

        // Cache vertices for erosion and sampling
        vertices = mesh.vertices;
    }

    // Applies erosion around a given world position, lowering nearby vertices.
    public void ApplyErosionAtPosition(Vector3 worldPosition)
    {
        // Skip erosion if disabled
        if (!enablePlayerErosion && player != null && worldPosition == player.position)
            return;

        // Convert to local space (terrain-relative position)
        Vector3 localPos = transform.InverseTransformPoint(worldPosition);

        // Loop through all vertices and lower those within erosion radius
        for (int i = 0; i < vertices.Length; i++)
        {
            Vector3 v = vertices[i];
            float dist = Vector2.Distance(new Vector2(v.x, v.z), new Vector2(localPos.x, localPos.z));
            // Falloff makes erosion stronger near the center
            if (dist < erosionRadius)
            {
                float falloff = 1 - Mathf.Pow(dist / erosionRadius, erosionFalloff);
                v.y -= erosionStrength * falloff * Time.deltaTime;
                vertices[i] = v;
            }
        }

        // Apply vertex changes to the mesh
        mesh.vertices = vertices;
        mesh.RecalculateNormals(); // Keeps lighting smooth
        meshCollider.sharedMesh = mesh; // Update collider for accurate physics
    }

    // Returns the terrain height at a specific world position.
    public float GetHeightAtPosition(Vector3 worldPos)
    {
        if (vertices == null || vertices.Length == 0) return 0f;

        int x = Mathf.Clamp(Mathf.RoundToInt(worldPos.x), 0, mapWidth - 1);
        int z = Mathf.Clamp(Mathf.RoundToInt(worldPos.z), 0, mapHeight - 1);
        // Convert (x,z) grid position into vertex index
        return vertices[z * (mapWidth + 1) + x].y;
    }

    // Keeps positions inside the terrain boundaries (prevents going off map).
    public Vector3 ClampToMap(Vector3 position, float margin = 1f)
    {
        float clampedX = Mathf.Clamp(position.x, margin, mapWidth - margin);
        float clampedZ = Mathf.Clamp(position.z, margin, mapHeight - margin);
        return new Vector3(clampedX, position.y, clampedZ);
    }

    // Returns a 0–1 normalized height for the given position.
    public float GetNormalizedHeightAtPosition(Vector3 worldPos)
    {
        return Mathf.InverseLerp(0f, meshHeightMultiplier, GetHeightAtPosition(worldPos));
    }

    // Rebuilds Unity's navigation mesh to match the updated terrain shape.
    public void RebuildNavMesh()
    {
        var surface = GetComponent<UnityEngine.AI.NavMeshSurface>();
        if (surface != null)
        {
            surface.BuildNavMesh();
        }
    }
}





